name: Bug Report
description: Bug report
labels: [bug]
title: "[Bug] "
body:
  - type: markdown
    attributes:
      value: |
        - Please read Troubleshooting and FAQs on the project's website before writing an issue to see if it helps solve your problem!
          https://auroraoss.com/guides/wiki-home/
        - Provide a general summary of the issue in the Title above.
        - Check if your issue or something similar has been reported before (if yes upvote/comment there)
        - Please use the latest stable release and note that we don't accept any bug reports for v.1.*, v.2.* & v.3.* anymore!
        - If you did not know already, everything between "<!---" & "~->" are comments in Markdown. These will not be visible unless when editing or viewed as raw file.
  - type: textarea
    attributes:
      label: Description
      description: Provide a detailed description to your issue itself, and why you consider it to be a bug
  - type: textarea
    attributes:
      label: Expected Behaviour
      description: Tell us what should happen
  - type: textarea
    attributes:
      label: Actual Behaviour
      description: Tell us what happens instead
  - type: textarea
    attributes:
      label: Steps to Reproduce
      description: Provide a link to a live example (screenshots/recording etc..), or a set of steps to reproduce the issue
      placeholder: |
        1. 
        2. 
        3. 
        4. 
  - type: textarea
    attributes:
      label: Environment
      description: Include as many relevant details about the environment you experienced the bug in.
      placeholder: |
        * Device model & codename: OnePlus 8T "instantnoodle"
        * Android version: 11.0.0
        * Arch: armeabi, armeabi-v7a, arm64-v8a
        * Aurora Store version: 4.0.2
        * Installation method: root/session/native/Aurora Services
        * OS: OxygenOS 11.0.1 (Android skin)
      value: |
        * Device model & codename:
        * Android version:
        * Aurora Store version:
        * Installation method:
        * OS:
  - type: textarea
    attributes:
      label: Logcat
      description: |
        If possible, include a logcat of the issue and upload on dogbin, nekobin, privatebin or any other bin of your choice, otherwise remove this comment section including the subtitle.
        The simplest way to get logs is by using Matlog or similar apps to start logging, then do your steps and save the logs as a .txt file.
        Upload the .txt file or copy/paste to https://del.dog/, https://nekobin.com/, https://privatebin.info/ and paste your link after this comment section.
  - type: textarea
    attributes:
      label: Examples
      description: If you have any examples, e.g. screenshots/videos/designs of the bug you found, paste or link them here.
  - type: textarea
    attributes:
      label: Additional context
      description: If you have more info to add, write it in this section, otherwise delete the subtitle and this comment.
  - type: textarea
    attributes:
      label: Possible solution
      description: If you believe to have a possible solution, write it in this section, otherwise delete the subtitle and this comment.
