name: Feature request
description: Feature request
labels: [enhancement]
title: "[Feature request] "
body:
  - type: markdown
    attributes:
      value: |
        - Please read Roadmap on the GitLab wiki before asking for a feature request!
        - Please search existing proposals to avoid creating duplicates. Some requests may also have been suggested on our Telegram channel, check it out: https://t.me/s/aurorabugsandsuggestions
        - Provide a general summary of the issue in the Title above.
        - If you did not know already, everything between "<!---" & "~->" are comments in Markdown. These will not be visible unless when editing or viewed as raw file.
  - type: textarea
    attributes:
      label: Description
      description: |
        Describe your idea as detailed as possible.
        If you have multiple ideas which are not directly connected to each other, 
        file an issue per idea. This makes it easy to implement one feature proposal at a time.
  - type: textarea
    attributes:
      label: Examples
      description: If you have any examples, e.g. screenshots/videos/designs of the feature you proposed, paste or link them here.
  - type: textarea
    attributes:
      label: Additional context
      description: If you have more info to add, write it in this section, otherwise delete the subtitle and this comment.
